BoxLayout:
    orientation: 'vertical'
    Button:
        id: cheese_button
        on_press: app.add_price
    Button:
        id: laptop_button
        on_press: app.add_price
    Button:
        id: plant_button
        on_press: app.add_price
    BoxLayout:
        orientation: 'horizontal'
        Label:
            id: output_label
            text: 'Total price $'
        Button:
            text: 'Reset'
            color: (1, 0, 0.5, 1)
            on_press: app.clear_fields()